version: "3.3"
services:
  db:
    build: ./mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      TZ: Asia/Taipei
    restart: always
  web:
    build: ./node_app
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      TZ: Asia/Taipei
    ports:
      - "8888:5000"
    depends_on:
      - db
    restart: on-failure
